title: Maolin Hou's Homepage
page-top-title: Maolin Hou
top-section-bg-text: Computer Science
home-subtitle: Maolin Hou&ensp;|&ensp;侯茂林
copyright-text: '&copy; Maolin Hou 2023-2024. All Rights Reserved.'
